# Script for generating general k-path for band structure calculation
# Author: Yujia Teng, Rutgers University
# 06/14/2025 - Creation of the script
# 01/12/2026 - Automatically reads the spin-flip operation based on outputs of find_sf_operations.py
# 03/2026    - Integrated find_sf_operations and compute_centroid_hybrid into one workflow
import numpy as np
import os
import sys
from typing import List, Tuple, Dict, Optional

# Try to import spin-flip operations finder
try:
    from find_sf_operations import run as find_sf_run
    FIND_SF_AVAILABLE = True
except ImportError:
    FIND_SF_AVAILABLE = False

# Try to import IBZ centroid calculator
try:
    from compute_centroid_hybrid import (run as compute_centroid,
                                         no_altermagnetism_reason,
                                         plot_spin_flip_figure,
                                         plot_spin_bz_figure,
                                         plot_spin_bz_top_view_figure)
    import matplotlib.pyplot as plt
    CENTROID_AVAILABLE = True
except ImportError:
    CENTROID_AVAILABLE = False
    no_altermagnetism_reason = None
    plot_spin_flip_figure = None
    plot_spin_bz_figure = None
    plot_spin_bz_top_view_figure = None
    plt = None

class KPointsModifier:
    def __init__(self):
        self.kpoints_data = []
        self.header_lines = []

    @staticmethod
    def _display_label(label: str) -> str:
        return 'GAMMA' if str(label).upper() in ('G', 'GAMMA', '螕') else str(label)

    @classmethod
    def _format_path(cls, path_segments) -> str:
        parts = []
        prev_end = None
        for seg_start, seg_end in path_segments:
            start = cls._display_label(seg_start)
            end = cls._display_label(seg_end)
            if seg_start != prev_end:
                parts.append(f"| {start}-{end}" if prev_end else f"{start}-{end}")
            else:
                parts.append(end)
            prev_end = seg_end
        return "-".join(parts).replace("-| ", " | ")

    @staticmethod
    def _format_matrix(op: np.ndarray) -> str:
        rows = []
        for row in op:
            row_str = " ".join(
                f"{int(x): 3d}" if float(x) % 1 == 0 else f"{x: .2f}"
                for x in row
            )
            rows.append(f"    [ {row_str} ]")
        return "\n".join(rows)

    @staticmethod
    def _count_written_segments(kpoints) -> int:
        count = 0
        for i in range(len(kpoints) - 1):
            start_point = kpoints[i]
            end_point = kpoints[i + 1]
            if start_point is None or end_point is None:
                continue
            if start_point[3] == end_point[3]:
                continue
            if {start_point[3], end_point[3]} == {"k", "k'"}:
                continue
            count += 1
        return count
    
    def read_kpoints_file(self, filename: str = "KPOINTS") -> bool:
        """Read KPOINTS file generated by VASPKIT"""
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
            
            # Parse header (first 4 lines)
            self.header_lines = [line.strip() for line in lines[:4]]
            
            # Parse k-points data
            self.kpoints_data = []
            for line in lines[4:]:
                line = line.strip()
                if line:  # Skip empty lines
                    parts = line.split()
                    if len(parts) >= 4:  # kx, ky, kz, label
                        kx, ky, kz = float(parts[0]), float(parts[1]), float(parts[2])
                        label = parts[-1] if len(parts) > 3 else ""
                        self.kpoints_data.append([kx, ky, kz, label])
            
            print(f"Successfully read {len(self.kpoints_data)} k-points from {filename}")
            return True
            
        except FileNotFoundError:
            print(f"Error: File {filename} not found!")
            return False
        except Exception as e:
            print(f"Error reading file: {e}")
            return False

    def load_flip_operations(self, filename: str = "spin_flip_operations.txt") -> List[np.ndarray]:
        """Reads pre-calculated rotation matrices from file"""
        matrices = []
        unique = []
        current_matrix = []
        if not os.path.exists(filename):
            legacy = (
                "preserve_spin_operations.txt"
                if filename == "spin_preserve_operations.txt"
                else "flip_spin_operations.txt"
            )
            if filename != legacy and os.path.exists(legacy):
                filename = legacy
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
            
            for line in lines:
                line = line.strip()
                if not line or line.startswith("#") or line.startswith("Operation"):
                    continue
                
                parts = line.split()
                if len(parts) == 3:
                    current_matrix.append([float(x) for x in parts])
                
                if len(current_matrix) == 3:
                    mat = np.array(current_matrix)
                    if not any(np.allclose(mat, ex, atol=1e-8) for ex in unique):
                        unique.append(mat)
                        matrices.append(mat)
                    current_matrix = []
            return matrices
        except FileNotFoundError:
            return []

    def load_preserve_operations(self, filename: str = "spin_preserve_operations.txt") -> List[np.ndarray]:
        """Reads pre-calculated spin-preserve rotation matrices from file."""
        return self.load_flip_operations(filename)

    def transform_kpoint(self, kpoint: List[float], transformation_matrix: np.ndarray) -> List[float]:
        """Apply transformation matrix to k-point: R^(-1)^T * k"""
        k = np.array(kpoint[:3])  # Take only x, y, z coordinates
        # Calculate R^(-1)^T
        R_inv_T = np.linalg.inv(transformation_matrix).T
        k_transformed = R_inv_T @ k
        return k_transformed.tolist()
    
    def insert_general_kpoints(self,
                               general_kpoint: List[float],
                               transformation_matrix: np.ndarray) -> List[List]:
        """
        Insert general k-points into every segment of the high symmetry path.
        Per-segment butterfly: for each (A,B) segment:
          - If A not yet opened: A-k | k'-A'
          - Connect A' to B'
          - Close: B'-k' | k-B
        Points already butterflied in earlier chains appear as plain segments.
        """
        if not self.kpoints_data:
            print("Error: No k-points data loaded. Please read KPOINTS file first.")
            return []

        k_prime = self.transform_kpoint(general_kpoint, transformation_matrix)
        kpt = general_kpoint
        kp  = k_prime

        def coords_eq(p, q, tol=1e-6):
            return abs(p[0]-q[0]) < tol and abs(p[1]-q[1]) < tol and abs(p[2]-q[2]) < tol

        def pt_key(p):
            return (round(p[0], 6), round(p[1], 6), round(p[2], 6))

        def is_gamma(p):
            return p[3].upper() in ['G', 'GAMMA', 'Γ']

        def get_prime(p):
            """Return primed version of p (Gamma stays unprimed)."""
            if is_gamma(p):
                return p.copy()
            tc = self.transform_kpoint(p, transformation_matrix)
            return [tc[0], tc[1], tc[2], f"{p[3]}'"]

        # --- Step 1: group flat kpoints_data into segment pairs ---
        raw = self.kpoints_data
        seg_pairs = [(raw[i], raw[i+1]) for i in range(0, len(raw) - 1, 2)]

        # --- Step 2: build connected chains ---
        chains = []
        current_chain = [seg_pairs[0][0], seg_pairs[0][1]]
        for sp_start, sp_end in seg_pairs[1:]:
            if coords_eq(current_chain[-1], sp_start):
                current_chain.append(sp_end)
            else:
                chains.append(current_chain)
                current_chain = [sp_start, sp_end]
        chains.append(current_chain)

        # --- Step 3: alternating plain / butterfly segments ---
        #
        # Pattern:
        #   Even-indexed segment --plain  (emit A, B)
        #   Odd-indexed segment  --butterfly (emit A, k, k', A', B', k', k, B)
        #
        # First chain: parity 0 --segment 0 is plain, segment 1 is butterfly, ...
        # Other chains: parity 1 --segment 0 is butterfly, segment 1 is plain, ...
        #
        # Consecutive segments share an endpoint; the duplicate is suppressed by
        # the same-label skip in write_kpoints_file and the display builder.
        # GAMMA is self-conjugate: get_prime(GAMMA) = GAMMA.
        path_sequence = []

        def emit_plain(A, B):
            path_sequence.append(A.copy())
            path_sequence.append(B.copy())

        def emit_butterfly(A, B):
            path_sequence.append(A.copy())
            path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
            path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
            path_sequence.append(get_prime(A))
            path_sequence.append(get_prime(B))
            # Universal rule: skip close if B already received butterfly treatment.
            # Applies to all points equally (GAMMA, X, W, etc.).
            if pt_key(B) not in butterflied:
                path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
                path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
                path_sequence.append(B.copy())

        butterflied = set()  # pt_key of points that have received butterfly treatment

        for ci, chain in enumerate(chains):
            # Dedup within chain (by coordinates, not labels)
            unique = []
            for pt in chain:
                if not unique or not coords_eq(unique[-1], pt):
                    unique.append(pt)

            # Degenerate chain: all points share the same coordinates
            # (e.g. U_0 --T for certain lattice parameters). Skip silently.
            if len(unique) < 2:
                labels = [p[3] for p in chain]
                print(f"  [Note] Part {ci+1} ({' - '.join(labels)}) skipped: "
                      f"endpoints coincide in coordinates")
                continue

            if ci > 0:
                path_sequence.append(None)

            start_parity = 0 if ci == 0 else 1

            parity = start_parity  # tracks alternation independently of s
            for s, (A, B) in enumerate(zip(unique, unique[1:])):
                A_key = pt_key(A)
                B_key = pt_key(B)
                is_last = (s == len(unique) - 2)
                # If A was already butterflied, continue from the side that is
                # already active. If the previous butterfly ended at A', the next
                # plain segment must be A'->B, not A'->A->B.
                if A_key in butterflied:
                    A_start = A
                    if path_sequence:
                        prev_pt = path_sequence[-1]
                        A_prime = get_prime(A)
                        if (prev_pt is not None and prev_pt[3] == A_prime[3]
                                and A_prime[3] != A[3]):
                            A_start = A_prime
                    emit_plain(A_start, B)
                    # B is a new endpoint --partial butterfly B-k|k'-B'
                    if B_key not in butterflied and is_last:
                        path_sequence.append(B.copy())
                        path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
                        path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
                        path_sequence.append(get_prime(B))
                        butterflied.add(B_key)
                    # Only hold parity when butterflied-A overrides a butterfly slot;
                    # if parity is already even (plain slot), advance normally.
                    if parity % 2 == 0:
                        parity += 1
                elif parity % 2 == 1:
                    emit_butterfly(A, B)
                    butterflied.add(A_key)
                    butterflied.add(B_key)
                    parity += 1
                else:
                    emit_plain(A, B)
                    parity += 1

            # After processing all segments in this chain, check if the last
            # point still lacks butterfly treatment (happens when chain 0 has
            # only 1 segment --the single plain pair leaves B un-butterflied).
            last_key = pt_key(unique[-1])
            if last_key not in butterflied:
                last_pt = unique[-1]
                path_sequence.append(last_pt.copy())
                path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
                path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
                path_sequence.append(get_prime(last_pt))
                butterflied.add(last_key)

        # Remove trailing sentinel
        if path_sequence and path_sequence[-1] is None:
            path_sequence.pop()

        # Print generated path as label string
        tokens = []  # list of label strings or '|' for breaks
        prev = None
        i = 0
        while i < len(path_sequence) - 1:
            cur = path_sequence[i]
            nxt = path_sequence[i + 1]
            # Chain boundary sentinel --insert break
            if cur is None or nxt is None:
                if tokens and tokens[-1] != '|':
                    tokens.append('|')
                i += 1
                continue
            # k↔k' connection --insert break
            if (cur[3] == "k" and nxt[3] == "k'") or \
               (cur[3] == "k'" and nxt[3] == "k"):
                if tokens and tokens[-1] != '|':
                    tokens.append('|')
                i += 1
                continue
            # same label --skip
            if cur[3] == nxt[3]:
                i += 1
                continue
            if prev != cur[3]:
                tokens.append(cur[3])
            tokens.append(nxt[3])
            prev = nxt[3]
            i += 1
        # Build display string: labels joined by '-', breaks become '|'.
        display_segments = []
        current_segment = []
        for t in tokens:
            if t == '|':
                if current_segment:
                    display_segments.append('-'.join(self._display_label(x) for x in current_segment))
                    current_segment = []
            else:
                current_segment.append(t)
        if current_segment:
            display_segments.append('-'.join(self._display_label(x) for x in current_segment))

        if len(display_segments) > 6:
            display = " | ".join(display_segments[:3] + ["..."] + display_segments[-3:])
        else:
            display = " | ".join(display_segments)
        print(f"Generated path: {display}")

        generated_segments = self._count_written_segments(path_sequence)
        generated_points = sum(1 for pt in path_sequence if pt is not None)
        print(f"Full path: {len(seg_pairs)} original segments -> "
              f"{generated_segments} generated segments, {generated_points} k-points")

        return path_sequence
    
    def write_kpoints_file(self, new_kpoints: List[List], output_file: str = "KPOINTS_modified",transformation_matrix: Optional[np.ndarray] = None):
        """Write modified KPOINTS file with proper Line-Mode format and discontinuity"""
        try:
            with open(output_file, 'w') as f:
                # Write header 
                if transformation_matrix is not None:
                    flat_matrix = np.array(transformation_matrix).flatten()
                    matrix_str = " ".join(f"{x:.8f}" for x in flat_matrix)
                    f.write(f"Obtained from Transformation Matrix: {matrix_str}\n")
                else:
                    f.write(f"{self.header_lines[0]}\n")
                
                f.write("   50\n")    # Number of points between each segment
                f.write(f"{self.header_lines[2]}\n")   # Line-Mode
                f.write(f"{self.header_lines[3]}\n")   # Reciprocal
                
                # Write k-points as segments with special handling for discontinuity
                i = 0
                while i < len(new_kpoints) - 1:
                    start_point = new_kpoints[i]
                    end_point = new_kpoints[i + 1]

                    # Skip chain boundary sentinels
                    if start_point is None or end_point is None:
                        i += 1
                        continue

                    # Skip any k to k' connections (there should be none)
                    if start_point[3] == "k" and end_point[3] == "k'":
                        i += 1
                        continue

                    if start_point[3] == "k'" and end_point[3] == "k":
                        i += 1
                        continue

                    if start_point[3] == end_point[3]:
                        i+=1
                        continue
                    
                    # Write segment: start_point -> end_point
                    f.write(f"   {start_point[0]:.10f}   {start_point[1]:.10f}   {start_point[2]:.10f}     {start_point[3]}\n")
                    f.write(f"   {end_point[0]:.10f}   {end_point[1]:.10f}   {end_point[2]:.10f}     {end_point[3]}\n")
                    
                    # Check if this creates a discontinuity (k is dead end)
                    if end_point[3] == "k":
                        f.write("\n")
                    else:
                        if i < len(new_kpoints) - 2:
                            f.write("\n")
                    i += 1
            
            print(f"Modified KPOINTS file written to: {output_file}")
            return True
            
        except Exception as e:
            print(f"Error writing file: {e}")
            return False

    def interactive_modify(self):
        """Interactive modification of KPOINTS file"""
        BOLD  = "\033[1m"
        RESET = "\033[0m"
        print("=== Altermagnetic K-Path Generator ===")

        # Step 0: Compute spin-flip operations from structure
        print(f"\n{BOLD}>>> Step 0: Spin symmetry{RESET}")
        print("Enter structure file (default: POSCAR, supports .vasp/.cif/.mcif): ", end='', flush=True)
        struct_file = input().strip()
        if not struct_file: struct_file = "POSCAR"

        # None = Step 0 not run; True = file freshly written; False = ran but no flip ops found
        _step0_wrote_flip_file = None
        _flip_file = 'spin_flip_operations.txt'

        if not os.path.exists(struct_file):
            print(f"[Note] '{struct_file}' not found. Skipping Step 0, using existing spin_flip_operations.txt")
            struct_file = None
        elif not FIND_SF_AVAILABLE:
            print("[Note] find_sf_operations.py not found. Skipping Step 0.")
            struct_file = None
        else:
            is_mcif = struct_file.lower().endswith('.mcif')
            if is_mcif:
                print("Detected .mcif file --magnetic moments will be read from file.")
                moments_str = ""
            else:
                print("Magnetic moments (atom order, trailing atoms auto-fill to 0): ", end='', flush=True)
                moments_str = input().strip()
            # Record mtime before so we know if find_sf_run wrote a fresh file
            _mtime_before = os.path.getmtime(_flip_file) if os.path.exists(_flip_file) else None
            sf_result = find_sf_run(struct_file, moments_str, verbose=False)
            _mtime_after = os.path.getmtime(_flip_file) if os.path.exists(_flip_file) else None
            _step0_wrote_flip_file = (
                _mtime_after is not None and _mtime_after != _mtime_before
            )
            if isinstance(sf_result, dict):
                _step0_wrote_flip_file = sf_result.get('spin_flip_operations', 0) > 0
                print(f"\nStructure: {sf_result['structure_file']}, atoms: {sf_result['num_atoms']}")
                print(f"Space Group: {sf_result['space_group']}")
                print(f"Point Group: {sf_result['point_group']}")
                print(f"Laue Group: {sf_result['laue_group']}")
                print(f"Magnetic SG: {sf_result['magnetic_space_group']}")
                print(f"Spin group: {sf_result['spin_group']}")
                unique_ops = sf_result.get('unique_point_operations',
                                           sf_result['total_operations'])
                print(f"Space-group operations: {sf_result['total_operations']} total")
                print(f"Point operations: {unique_ops} unique")
                print("Actual point operations: "
                      f"{sf_result['actual_spin_flip_point_operations']} spin-flip, "
                      f"{sf_result['actual_spin_preserve_point_operations']} spin-preserving")
                print("Inversion-extended k operations: "
                      f"{sf_result['extended_spin_flip_point_operations']} spin-flip, "
                      f"{sf_result['extended_spin_preserve_point_operations']} spin-preserving "
                      f"({sf_result['extended_spin_flip_operations']} + "
                      f"{sf_result['extended_spin_preserve_operations']} with translations)")
                if sf_result['spin_split_diagnostic']:
                    print(f"Diagnostic: {sf_result['spin_split_diagnostic']}")
                print(f"Saved: {', '.join(sf_result['saved_files'])}")

        # Step 1: High-symmetry k-path (auto from seekpath or user file)
        print(f"\n{BOLD}>>> Step 1: High-symmetry k-path{RESET}")
        centroid_result = None
        display_figures = []

        if struct_file and CENTROID_AVAILABLE:
            try:
                centroid_result = compute_centroid(struct_file, output_dir='.', show_plot=True,
                                                   defer_show=True, verbose=False)
                display_figures.extend(centroid_result.get('display_figures', []))
                sp_path   = centroid_result['sp_path']
                sp_coords = centroid_result['sp_point_coords']
                print(f"IBZ type: {centroid_result.get('sc_type', centroid_result.get('seekpath_bravais', 'unknown'))}")
                print(f"Path: {self._format_path(sp_path)}")
                print("Press [Enter] to use this path, or type a filename to load your own: ", end='', flush=True)
                path_choice = input().strip()
                if not path_choice:
                    # Build kpoints_data in the same HPKOT/SeeK-path convention
                    # as Figure 1.  lattice_kpoints.py may include curated
                    # closure vertices for the hull, but ibz_kpath contains only
                    # the public band-path labels.  path_kpoints_frac keeps
                    # optional path-only labels such as H_2 available without
                    # adding them to the centroid hull.
                    self.kpoints_data = []
                    sc_type_auto = centroid_result.get('sc_type', '')
                    if 'ibz_kpath' in centroid_result and 'ibz_kpoints_frac' in centroid_result:
                        self.header_lines = [f'K-Path generated by AlterSeeK-Path (HPKOT {sc_type_auto})',
                                             '20', 'Line-Mode', 'Reciprocal']
                        ibz_coords = centroid_result.get(
                            'path_kpoints_frac',
                            centroid_result['ibz_kpoints_frac']
                        )
                        auto_path = centroid_result['ibz_kpath']
                        for seg_start, seg_end in auto_path:
                            for label in (seg_start, seg_end):
                                coords = ibz_coords[label]
                                self.kpoints_data.append([coords[0], coords[1], coords[2], label])
                        print(f"Using HPKOT {sc_type_auto} path ({len(auto_path)} segments, {len(self.kpoints_data)} k-points)")
                    else:
                        self.header_lines = ['K-Path generated by AlterSeeK-Path (seekpath)', '20', 'Line-Mode', 'Reciprocal']
                        for seg_start, seg_end in sp_path:
                            for label in (seg_start, seg_end):
                                coords = sp_coords[label]
                                self.kpoints_data.append([coords[0], coords[1], coords[2], label])
                        print(f"Using auto-generated path ({len(sp_path)} segments, {len(self.kpoints_data)} k-points)")
                else:
                    if not self.read_kpoints_file(path_choice): return
            except Exception as e:
                print(f"[Warning] Auto path generation failed: {e}")
                print("Falling back to manual file input.")
                print("Enter KPOINTS file name (default: KPATH.in): ", end='', flush=True)
                filename = input().strip()
                if not filename: filename = "KPATH.in"
                if not self.read_kpoints_file(filename): return
        else:
            print("Enter KPOINTS file name (default: KPATH.in): ", end='', flush=True)
            filename = input().strip()
            if not filename: filename = "KPATH.in"
            if not self.read_kpoints_file(filename): return

        # Laue groups -1, -3, and m-3 do not have a one-dimensional,
        # nonidentical inversion-even irrep, so no altermagnetic splitting is
        # possible. Write the ordinary IBZ path without butterfly insertion.
        no_altermag = None
        if centroid_result is not None:
            no_altermag = centroid_result.get('no_altermagnetism')
            if no_altermag is None and no_altermagnetism_reason is not None:
                no_altermag = no_altermagnetism_reason(
                    centroid_result.get('point_group'),
                    centroid_result.get('spacegroup'),
                )
        if no_altermag:
            laue = no_altermag.get('laue_group', 'unknown')
            print(f"\n[Note] Laue group {laue}: no altermagnetism.")
            print("Writing standard IBZ k-path.")
            print(f"\n{BOLD}>>> Step 5: Save{RESET}")
            print("Enter output filename (default: KPOINTS_modified): ", end='', flush=True)
            output_file = input().strip()
            if not output_file:
                output_file = "KPOINTS_modified"
            # Write the plain IBZ path (no butterfly, no transformation).
            self.write_kpoints_file(self.kpoints_data, output_file, None)
            print(f"\nDone.")
            if display_figures and plt is not None:
                print('Displaying generated figure(s)...')
                plt.show()
                for fig in display_figures:
                    save_after_show = getattr(fig, '_alterseek_save_after_show', None)
                    if save_after_show is not None:
                        save_after_show()
            return

        # Step 2: Auto-compute or manually enter general k-point
        print(f"\n{BOLD}>>> Step 2: General k-point{RESET}")
        general_kpoint = None

        if centroid_result is not None:
            try:
                c = centroid_result['centroid_frac']
                general_kpoint = [c[0], c[1], c[2]]
                print(f"IBZ centroid: [{c[0]:.6f}, {c[1]:.6f}, {c[2]:.6f}]")
            except Exception as e:
                print(f"[Warning] Centroid retrieval failed: {e}")
        elif struct_file and CENTROID_AVAILABLE:
            try:
                result = compute_centroid(struct_file, output_dir='.', show_plot=True,
                                          defer_show=True, verbose=False)
                display_figures.extend(result.get('display_figures', []))
                c = result['centroid_frac']
                general_kpoint = [c[0], c[1], c[2]]
                print(f"IBZ centroid: [{c[0]:.6f}, {c[1]:.6f}, {c[2]:.6f}]")
            except Exception as e:
                print(f"[Warning] Centroid computation failed: {e}")

        # Append centroid to spin_operations.txt for reference
        if general_kpoint is not None:
            try:
                with open("spin_operations.txt", "a") as f:
                    f.write(f"\nGeneral k-point (IBZ centroid, fractional): "
                            f"[{general_kpoint[0]:.6f}, {general_kpoint[1]:.6f}, {general_kpoint[2]:.6f}]\n")
            except Exception:
                pass

        if general_kpoint is None:
            print("Format: kx ky kz (space-separated)")
            while True:
                try:
                    print("Enter k-point: ", end='', flush=True)
                    k_input = input().strip().split()
                    if len(k_input) == 3:
                        general_kpoint = [float(x) for x in k_input]
                        break
                    else:
                        print("Please enter exactly 3 coordinates.")
                except ValueError:
                    print("Invalid input. Please enter three numbers.")

        # Step 3: Input transformation matrix
        print(f"\n{BOLD}>>> Step 3: Spin-flip operation{RESET}")
        if _step0_wrote_flip_file is False:
            # Step 0 ran but found no flip ops for this structure.
            # Don't load a stale file from a previous run on a different structure.
            print("[Note] Step 0 found no spin-flip operations --skipping any existing spin_flip_operations.txt.")
            flip_ops = []
        else:
            flip_ops = self.load_flip_operations()

        # Always include inversion-extended spatial partners. The spin-flip
        # classification comes from the spin rotation in find_sf_operations.py;
        # multiplying the spatial operation by inversion does not change that
        # spin-flip status. Deduplicate after extension.
        if flip_ops:
            expanded = list(flip_ops)
            for op in flip_ops:
                neg_op = -np.array(op, dtype=float)
                if not any(np.allclose(neg_op, ex, atol=1e-8) for ex in expanded):
                    expanded.append(neg_op)
            flip_ops = expanded

        expected_flip_ops = None
        if centroid_result is not None and centroid_result.get('unique_ops') is not None:
            expected_flip_ops = max(1, len(centroid_result['unique_ops']) // 2)
        if flip_ops and expected_flip_ops is not None and len(flip_ops) < expected_flip_ops:
            preserve_ops = self.load_preserve_operations()
            supplemented = list(flip_ops)
            for op in preserve_ops:
                for cand in (np.array(op, dtype=float), -np.array(op, dtype=float)):
                    if not any(np.allclose(cand, ex, atol=1e-8) for ex in supplemented):
                        supplemented.append(cand)
                    if len(supplemented) >= expected_flip_ops:
                        break
                if len(supplemented) >= expected_flip_ops:
                    break
            if len(supplemented) > len(flip_ops):
                print(f"[Note] Added {len(supplemented) - len(flip_ops)} inversion-extended "
                      f"spin-preserve k-space partners to complete the spin-flip set.")
                flip_ops = supplemented

        R = None
        if flip_ops:
            print(f"Found {len(flip_ops)} spin-flip operations.")
            print("Default R: Option 1")
            while R is None:
                print("Press [Enter] to use default, type a number, 'list' to show matrices, or 'manual': ", end='', flush=True)
                choice = input().strip().lower()

                if not choice:
                    R = flip_ops[0]
                    print("Selected: Option 1")
                elif choice == 'list':
                    for i, op in enumerate(flip_ops):
                        print(f"\n  Option {i+1}:")
                        print(self._format_matrix(op))
                    print()
                elif choice == 'manual':
                    break
                else:
                    try:
                        idx = int(choice) - 1
                        if 0 <= idx < len(flip_ops):
                            R = flip_ops[idx]
                            print(f"Selected: Option {idx+1}")
                        else:
                            print(f"Please choose 1-{len(flip_ops)}, 'list', or 'manual'.")
                    except ValueError:
                        print(f"Please choose 1-{len(flip_ops)}, 'list', or 'manual'.")

        if R is None:
            print("Enter custom transformation matrix R.")
            print("Enter row by row (3 numbers per row, space-separated):")
            transformation_matrix = []
            for i in range(3):
                while True:
                    try:
                        print(f"Row {i+1}: ", end='', flush=True)
                        row_input = input().strip().split()
                        if len(row_input) == 3:
                            transformation_matrix.append([float(x) for x in row_input])
                            break
                        print("Please enter exactly 3 numbers.")
                    except ValueError: pass
            R = np.array(transformation_matrix)
        
        # Step 4: Process k-points
        print(f"\n{BOLD}>>> Step 4: Build altermagnetic path{RESET}")

        # find_sf_operations.py writes spinspg rotations in the input file's
        # fractional basis.  KPOINTS/IBZ coordinates are in the seekpath primitive
        # reciprocal basis, which can differ for centered lattices (e.g. BCT, RHL).
        # Convert through Cartesian k-space so k', Figure 2, and the path all use
        # the same physical spin-flip operation:
        #   R_cart_k       = b_input.T @ inv(R_input).T @ inv(b_input.T)
        #   R_prim^{-T}    = inv(b_prim.T) @ R_cart_k @ b_prim.T
        R_cart_for_plot = None
        flip_ops_for_plot = flip_ops
        if centroid_result is not None and 'b_matrix' in centroid_result:
            _b_input = np.array(centroid_result.get('b_matrix_input',
                                                    centroid_result['b_matrix_conv']), dtype=float)
            _b_prim = np.array(centroid_result['b_matrix'], dtype=float)
            def _convert_input_frac_R_to_prim(_R):
                _R_arr = np.array(_R, dtype=float)
                _R_cart = _b_input.T @ np.linalg.inv(_R_arr).T @ np.linalg.inv(_b_input.T)
                _R_prim_inv_T = np.linalg.inv(_b_prim.T) @ _R_cart @ _b_prim.T
                return np.linalg.inv(_R_prim_inv_T.T), _R_cart

            R_for_kpts, R_cart_for_plot = _convert_input_frac_R_to_prim(R)
            if flip_ops:
                flip_ops_for_plot = [
                    _convert_input_frac_R_to_prim(op)[0] for op in flip_ops
                ]
            print("[Basis] Converted R from input-cell basis to primitive basis.")
        else:
            R_for_kpts = R

        # Calculate and show k'
        k_prime = self.transform_kpoint(general_kpoint, R_for_kpts)
        print(f"k' = [{k_prime[0]:.4f}, {k_prime[1]:.4f}, {k_prime[2]:.4f}]")

        try:
            new_kpoints = self.insert_general_kpoints(general_kpoint, R_for_kpts)

            if new_kpoints:
                # Generate spin-flip connection figure
                if (centroid_result is not None and plot_spin_flip_figure is not None
                        and 'b_matrix' in centroid_result):
                    try:
                        basename = (os.path.splitext(os.path.basename(struct_file))[0]
                                    if struct_file else 'output')
                        sc_type = centroid_result.get('sc_type', 'BZ')
                        fig_path = f'{basename}_spinflip_{sc_type}.png'
                        spin_flip_fig = plot_spin_flip_figure(
                            b_matrix=centroid_result['b_matrix'],
                            bz_loops=centroid_result['bz_loops'],
                            bz_center=centroid_result['bz_center'],
                            bz_span=centroid_result['bz_span'],
                            kpoints_data=self.kpoints_data,
                            ibz_kpoints_frac=centroid_result.get('ibz_kpoints_frac', {}),
                            hull_pts=centroid_result.get('hull_pts'),
                            hull_simplices=centroid_result.get('hull_simplices'),
                            centroid_frac=general_kpoint,
                            R=R_for_kpts,
                            output_path=fig_path,
                            R_cart=R_cart_for_plot,
                            elev=centroid_result.get('elev', 25),
                            azim=centroid_result.get('azim', -55),
                            show_plot=True,
                            block=False,
                            path_sequence=new_kpoints,
                            defer_show=True,
                            unique_ops=centroid_result.get('unique_ops'),
                        )
                        if spin_flip_fig is not None:
                            display_figures.append(spin_flip_fig)
                    except Exception as _e:
                        print(f"[Warning] Could not generate spin-flip figure: {_e}")

                # Generate spin-up/spin-down full-BZ coloring figure
                if (centroid_result is not None and plot_spin_bz_figure is not None
                        and 'unique_ops' in centroid_result):
                    try:
                        bz_fig_path = f'{basename}_spinbz_{sc_type}.png'
                        spin_bz_fig = plot_spin_bz_figure(
                            b_matrix=centroid_result['b_matrix'],
                            bz_loops=centroid_result['bz_loops'],
                            bz_center=centroid_result['bz_center'],
                            bz_span=centroid_result['bz_span'],
                            unique_ops=centroid_result['unique_ops'],
                            centroid_cart=centroid_result['centroid_cart'],
                            hull_pts=centroid_result.get('hull_pts'),
                            hull_simplices=centroid_result.get('hull_simplices'),
                            R=R_for_kpts,
                            output_path=bz_fig_path,
                            flip_ops_frac=flip_ops_for_plot if flip_ops_for_plot else None,
                            elev=centroid_result.get('elev', 25),
                            azim=centroid_result.get('azim', -55),
                            show_plot=True,
                            defer_show=True,
                        )
                        if spin_bz_fig is not None:
                            display_figures.append(spin_bz_fig)
                    except Exception as _e:
                        print(f"[Warning] Could not generate spin-BZ figure: {_e}")

                # Generate kz=0 top-view spin-BZ coloring figure
                if (centroid_result is not None and plot_spin_bz_top_view_figure is not None
                        and 'unique_ops' in centroid_result):
                    try:
                        top_fig_path = f'{basename}_spinbz_top_{sc_type}.png'
                        spin_bz_top_fig = plot_spin_bz_top_view_figure(
                            b_matrix=centroid_result['b_matrix'],
                            bz_loops=centroid_result['bz_loops'],
                            unique_ops=centroid_result['unique_ops'],
                            centroid_cart=centroid_result['centroid_cart'],
                            hull_pts=centroid_result.get('hull_pts'),
                            hull_simplices=centroid_result.get('hull_simplices'),
                            R=R_for_kpts,
                            output_path=top_fig_path,
                            flip_ops_frac=flip_ops_for_plot if flip_ops_for_plot else None,
                            show_plot=True,
                            defer_show=True,
                            z0=0.0,
                        )
                        if spin_bz_top_fig is not None:
                            display_figures.append(spin_bz_top_fig)
                    except Exception as _e:
                        print(f"[Warning] Could not generate spin-BZ top-view figure: {_e}")
                # Step 5: Save modified file
                print(f"\n{BOLD}>>> Step 5: Save{RESET}")
                print("Enter output filename (default: KPOINTS_modified): ", end='', flush=True)
                output_file = input().strip()
                if not output_file:
                    output_file = "KPOINTS_modified"
                
                self.write_kpoints_file(new_kpoints, output_file, R_for_kpts)
                print(f"\nDone.")
                if display_figures and plt is not None:
                    print('Displaying generated figures...')
                    plt.show()
                    for fig in display_figures:
                        save_after_show = getattr(fig, '_alterseek_save_after_show', None)
                        if save_after_show is not None:
                            save_after_show()
            else:
                print("Error: Failed to process k-points.")
                
        except Exception as e:
            print(f"Error processing k-points: {e}")

def main():
    if len(sys.argv) > 1 and sys.argv[1] in {"-h", "--help"}:
        print("usage: alterseek-path [bandplot] [options]\n")
        print("Run without arguments to generate an altermagnetic KPOINTS path interactively.")
        print("Subcommands:")
        print("  bandplot    Plot spin-resolved bands from KLABELS and reformatted band data.")
        print("\nFor band plotting options, run: alterseek-path bandplot --help")
        return

    if len(sys.argv) > 1 and sys.argv[1].lower() in {"bandplot", "plot-band", "plot"}:
        from plot_alterband import main as plot_alterband_main
        plot_alterband_main(sys.argv[2:])
        return

    modifier = KPointsModifier()
    modifier.interactive_modify()


if __name__ == "__main__":
    main()

