# Script for generating general k-path for band structure calculation
# Author: Yujia Teng, Rutgers University
# 06/14/2025 - Creation of the script
# 01/12/2026 - Automatically reads the spin-flip operation based on outputs of find_sf_operations.py
# 03/2026    - Integrated find_sf_operations and compute_centroid_hybrid into one workflow
import numpy as np
import os
from typing import List, Tuple, Dict, Optional

# Try to import spin-flip operations finder
try:
    from find_sf_operations import run as find_sf_run
    FIND_SF_AVAILABLE = True
except ImportError:
    FIND_SF_AVAILABLE = False

# Try to import IBZ centroid calculator
try:
    from compute_centroid_hybrid import run as compute_centroid
    CENTROID_AVAILABLE = True
except ImportError:
    CENTROID_AVAILABLE = False

class KPointsModifier:
    def __init__(self):
        self.kpoints_data = []
        self.header_lines = []
    
    def read_kpoints_file(self, filename: str = "KPOINTS") -> bool:
        """Read KPOINTS file generated by VASPKIT"""
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
            
            # Parse header (first 4 lines)
            self.header_lines = [line.strip() for line in lines[:4]]
            
            # Parse k-points data
            self.kpoints_data = []
            for line in lines[4:]:
                line = line.strip()
                if line:  # Skip empty lines
                    parts = line.split()
                    if len(parts) >= 4:  # kx, ky, kz, label
                        kx, ky, kz = float(parts[0]), float(parts[1]), float(parts[2])
                        label = parts[-1] if len(parts) > 3 else ""
                        self.kpoints_data.append([kx, ky, kz, label])
            
            print(f"Successfully read {len(self.kpoints_data)} k-points from {filename}")
            return True
            
        except FileNotFoundError:
            print(f"Error: File {filename} not found!")
            return False
        except Exception as e:
            print(f"Error reading file: {e}")
            return False

    def load_flip_operations(self, filename: str = "flip_spin_operations.txt") -> List[np.ndarray]:
        """Reads pre-calculated rotation matrices from file"""
        matrices = []
        current_matrix = []
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
            
            for line in lines:
                line = line.strip()
                if not line or line.startswith("#") or line.startswith("Operation"):
                    continue
                
                parts = line.split()
                if len(parts) == 3:
                    current_matrix.append([float(x) for x in parts])
                
                if len(current_matrix) == 3:
                    matrices.append(np.array(current_matrix))
                    current_matrix = []
            return matrices
        except FileNotFoundError:
            return []
    
    def transform_kpoint(self, kpoint: List[float], transformation_matrix: np.ndarray) -> List[float]:
        """Apply transformation matrix to k-point: R^(-1)^T * k"""
        k = np.array(kpoint[:3])  # Take only x, y, z coordinates
        # Calculate R^(-1)^T
        R_inv_T = np.linalg.inv(transformation_matrix).T
        k_transformed = R_inv_T @ k
        return k_transformed.tolist()
    
    def insert_general_kpoints(self,
                               general_kpoint: List[float],
                               transformation_matrix: np.ndarray) -> List[List]:
        """
        Insert general k-points into every segment of the high symmetry path.
        Per-segment butterfly: for each (A,B) segment:
          - If A not yet opened: A-k | k'-A'
          - Connect A' to B'
          - Close: B'-k' | k-B
        Points already butterflied in earlier chains appear as plain segments.
        """
        if not self.kpoints_data:
            print("Error: No k-points data loaded. Please read KPOINTS file first.")
            return []

        k_prime = self.transform_kpoint(general_kpoint, transformation_matrix)
        kpt = general_kpoint
        kp  = k_prime

        def coords_eq(p, q, tol=1e-6):
            return abs(p[0]-q[0]) < tol and abs(p[1]-q[1]) < tol and abs(p[2]-q[2]) < tol

        def pt_key(p):
            return (round(p[0], 6), round(p[1], 6), round(p[2], 6))

        def is_gamma(p):
            return p[3].upper() in ['G', 'GAMMA', 'Γ']

        def get_prime(p):
            """Return primed version of p (Gamma stays unprimed)."""
            if is_gamma(p):
                return p.copy()
            tc = self.transform_kpoint(p, transformation_matrix)
            return [tc[0], tc[1], tc[2], f"{p[3]}'"]

        # --- Step 1: group flat kpoints_data into segment pairs ---
        raw = self.kpoints_data
        seg_pairs = [(raw[i], raw[i+1]) for i in range(0, len(raw) - 1, 2)]

        # --- Step 2: build connected chains ---
        chains = []
        current_chain = [seg_pairs[0][0], seg_pairs[0][1]]
        for sp_start, sp_end in seg_pairs[1:]:
            if coords_eq(current_chain[-1], sp_start):
                current_chain.append(sp_end)
            else:
                chains.append(current_chain)
                current_chain = [sp_start, sp_end]
        chains.append(current_chain)

        # Display the original high-symmetry path for reference
        hs_parts = []
        for ci, chain in enumerate(chains):
            labels = [p[3] for p in chain]
            if ci > 0:
                hs_parts.append('|')
            hs_parts.append('-'.join(labels))
        print(f"High-symmetry path: {''.join(hs_parts)}")
        print(f"Found {len(chains)} path segment(s):")
        for ci, chain in enumerate(chains):
            labels = [p[3] for p in chain]
            print(f"  Part {ci+1}: {' - '.join(labels)}")

        # --- Step 3: alternating plain / butterfly segments ---
        #
        # Pattern:
        #   Even-indexed segment → plain  (emit A, B)
        #   Odd-indexed segment  → butterfly (emit A, k, k', A', B', k', k, B)
        #
        # First chain: parity 0 → segment 0 is plain, segment 1 is butterfly, ...
        # Other chains: parity 1 → segment 0 is butterfly, segment 1 is plain, ...
        #
        # Consecutive segments share an endpoint; the duplicate is suppressed by
        # the same-label skip in write_kpoints_file and the display builder.
        # GAMMA is self-conjugate: get_prime(GAMMA) = GAMMA.
        path_sequence = []

        def emit_plain(A, B):
            path_sequence.append(A.copy())
            path_sequence.append(B.copy())

        def emit_butterfly(A, B):
            path_sequence.append(A.copy())
            path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
            path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
            path_sequence.append(get_prime(A))
            path_sequence.append(get_prime(B))
            # Universal rule: skip close if B already received butterfly treatment.
            # Applies to all points equally (GAMMA, X, W, etc.).
            if pt_key(B) not in butterflied:
                path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
                path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
                path_sequence.append(B.copy())

        butterflied = set()  # pt_key of points that have received butterfly treatment

        for ci, chain in enumerate(chains):
            # Dedup within chain (by coordinates, not labels)
            unique = []
            for pt in chain:
                if not unique or not coords_eq(unique[-1], pt):
                    unique.append(pt)

            # Degenerate chain: all points share the same coordinates
            # (e.g. U_0 ≡ T for certain lattice parameters). Skip silently.
            if len(unique) < 2:
                labels = [p[3] for p in chain]
                print(f"  [Note] Part {ci+1} ({' - '.join(labels)}) skipped: "
                      f"endpoints coincide in coordinates")
                continue

            if ci > 0:
                path_sequence.append(None)

            start_parity = 0 if ci == 0 else 1

            parity = start_parity  # tracks alternation independently of s
            for s, (A, B) in enumerate(zip(unique, unique[1:])):
                A_key = pt_key(A)
                B_key = pt_key(B)
                is_last = (s == len(unique) - 2)
                # If A was already butterflied, emit plain (skip re-opening)
                if A_key in butterflied:
                    emit_plain(A, B)
                    # B is a new endpoint → partial butterfly B-k|k'-B'
                    if B_key not in butterflied and is_last:
                        path_sequence.append(B.copy())
                        path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
                        path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
                        path_sequence.append(get_prime(B))
                        butterflied.add(B_key)
                    # Only hold parity when butterflied-A overrides a butterfly slot;
                    # if parity is already even (plain slot), advance normally.
                    if parity % 2 == 0:
                        parity += 1
                elif parity % 2 == 1:
                    emit_butterfly(A, B)
                    butterflied.add(A_key)
                    butterflied.add(B_key)
                    parity += 1
                else:
                    emit_plain(A, B)
                    parity += 1

            # After processing all segments in this chain, check if the last
            # point still lacks butterfly treatment (happens when chain 0 has
            # only 1 segment → the single plain pair leaves B un-butterflied).
            last_key = pt_key(unique[-1])
            if last_key not in butterflied:
                last_pt = unique[-1]
                path_sequence.append(last_pt.copy())
                path_sequence.append([kpt[0], kpt[1], kpt[2], "k"])
                path_sequence.append([kp[0],  kp[1],  kp[2],  "k'"])
                path_sequence.append(get_prime(last_pt))
                butterflied.add(last_key)

        # Remove trailing sentinel
        if path_sequence and path_sequence[-1] is None:
            path_sequence.pop()

        # Print generated path as label string
        tokens = []  # list of label strings or '|' for breaks
        prev = None
        i = 0
        while i < len(path_sequence) - 1:
            cur = path_sequence[i]
            nxt = path_sequence[i + 1]
            # Chain boundary sentinel → insert break
            if cur is None or nxt is None:
                if tokens and tokens[-1] != '|':
                    tokens.append('|')
                i += 1
                continue
            # k↔k' connection → insert break
            if (cur[3] == "k" and nxt[3] == "k'") or \
               (cur[3] == "k'" and nxt[3] == "k"):
                if tokens and tokens[-1] != '|':
                    tokens.append('|')
                i += 1
                continue
            # same label → skip
            if cur[3] == nxt[3]:
                i += 1
                continue
            if prev != cur[3]:
                tokens.append(cur[3])
            tokens.append(nxt[3])
            prev = nxt[3]
            i += 1
        # Build display string: labels joined by '-', breaks become '|'
        display = ''
        for t in tokens:
            if t == '|':
                display = display.rstrip('-') + '|'
            else:
                display += t + '-'
        display = display.rstrip('-').rstrip('|')
        print(f"Generated path: {display}")

        return path_sequence
    
    def write_kpoints_file(self, new_kpoints: List[List], output_file: str = "KPOINTS_modified",transformation_matrix: Optional[np.ndarray] = None):
        """Write modified KPOINTS file with proper Line-Mode format and discontinuity"""
        try:
            with open(output_file, 'w') as f:
                # Write header 
                if transformation_matrix is not None:
                    flat_matrix = transformation_matrix.flatten()
                    matrix_str = " ".join(f"{x:.8f}" for x in flat_matrix)
                    f.write(f"Obtained from Transformation Matrix: {matrix_str}\n")
                else:
                    f.write(f"{self.header_lines[0]}\n")
                
                f.write("   50\n")    # Number of points between each segment
                f.write(f"{self.header_lines[2]}\n")   # Line-Mode
                f.write(f"{self.header_lines[3]}\n")   # Reciprocal
                
                # Write k-points as segments with special handling for discontinuity
                i = 0
                while i < len(new_kpoints) - 1:
                    start_point = new_kpoints[i]
                    end_point = new_kpoints[i + 1]

                    # Skip chain boundary sentinels
                    if start_point is None or end_point is None:
                        i += 1
                        continue

                    # Skip any k to k' connections (there should be none)
                    if start_point[3] == "k" and end_point[3] == "k'":
                        i += 1
                        continue

                    if start_point[3] == "k'" and end_point[3] == "k":
                        i += 1
                        continue

                    if start_point[3] == end_point[3]:
                        i+=1
                        continue
                    
                    # Write segment: start_point -> end_point
                    f.write(f"   {start_point[0]:.10f}   {start_point[1]:.10f}   {start_point[2]:.10f}     {start_point[3]}\n")
                    f.write(f"   {end_point[0]:.10f}   {end_point[1]:.10f}   {end_point[2]:.10f}     {end_point[3]}\n")
                    
                    # Check if this creates a discontinuity (k is dead end)
                    if end_point[3] == "k":
                        f.write("\n")
                    else:
                        if i < len(new_kpoints) - 2:
                            f.write("\n")
                    i += 1
            
            print(f"Modified KPOINTS file written to: {output_file}")
            return True
            
        except Exception as e:
            print(f"Error writing file: {e}")
            return False

    def interactive_modify(self):
        """Interactive modification of KPOINTS file"""
        BOLD  = "\033[1m"
        RESET = "\033[0m"
        print("=== Altermagnetic K-Path Generator ===")

        # Step 0: Compute spin-flip operations from structure
        print(f"\n{BOLD}>>> Step 0: Compute spin-flip symmetry operations{RESET}")
        print("Enter structure file (default: POSCAR, supports .vasp/.cif/.mcif): ", end='', flush=True)
        struct_file = input().strip()
        if not struct_file: struct_file = "POSCAR"

        if not os.path.exists(struct_file):
            print(f"[Note] '{struct_file}' not found. Skipping Step 0, using existing flip_spin_operations.txt")
            struct_file = None
        elif not FIND_SF_AVAILABLE:
            print("[Note] find_sf_operations.py not found. Skipping Step 0.")
            struct_file = None
        else:
            is_mcif = struct_file.lower().endswith('.mcif')
            if is_mcif:
                print("Detected .mcif file — magnetic moments will be read from file.")
                moments_str = ""
            else:
                print("Enter magnetic moments in atom order from structure file (space-separated).")
                print("  Trailing non-magnetic atoms auto-fill to 0 (e.g., just '1 -1' if mag atoms come first).")
                print("  If non-magnetic atoms appear first, include 0s (e.g., '0 0 1 -1').")
                print("Moments: ", end='', flush=True)
                moments_str = input().strip()
            find_sf_run(struct_file, moments_str)

        # Step 1: High-symmetry k-path (auto from seekpath or user file)
        print(f"\n{BOLD}>>> Step 1: High-symmetry k-path{RESET}")
        centroid_result = None

        if struct_file and CENTROID_AVAILABLE:
            try:
                print(f"Computing IBZ centroid and k-path from '{struct_file}'...")
                centroid_result = compute_centroid(struct_file, output_dir='.', show_plot=True)
                sp_path   = centroid_result['sp_path']
                sp_coords = centroid_result['sp_point_coords']
                # Build human-readable path string for display
                parts = []
                prev_end = None
                for seg_s, seg_e in sp_path:
                    if seg_s != prev_end:
                        parts.append(f"|{seg_s}-{seg_e}" if prev_end else f"{seg_s}-{seg_e}")
                    else:
                        parts.append(seg_e)
                    prev_end = seg_e
                print(f"Auto-generated path: {'-'.join(parts)}")
                print("Press [Enter] to use this path, or type a filename to load your own: ", end='', flush=True)
                path_choice = input().strip()
                if not path_choice:
                    # Build kpoints_data from seekpath result
                    self.kpoints_data = []
                    self.header_lines = ['K-Path generated by AlterSeeK-Path (seekpath)', '20', 'Line-Mode', 'Reciprocal']
                    for seg_start, seg_end in sp_path:
                        for label in (seg_start, seg_end):
                            coords = sp_coords[label]
                            self.kpoints_data.append([coords[0], coords[1], coords[2], label])
                    print(f"Using auto-generated path ({len(sp_path)} segments, {len(self.kpoints_data)} k-points)")
                else:
                    if not self.read_kpoints_file(path_choice): return
            except Exception as e:
                print(f"[Warning] Auto path generation failed: {e}")
                print("Falling back to manual file input.")
                print("Enter KPOINTS file name (default: KPATH.in): ", end='', flush=True)
                filename = input().strip()
                if not filename: filename = "KPATH.in"
                if not self.read_kpoints_file(filename): return
        else:
            print("Enter KPOINTS file name (default: KPATH.in): ", end='', flush=True)
            filename = input().strip()
            if not filename: filename = "KPATH.in"
            if not self.read_kpoints_file(filename): return

        # Triclinic (space groups 1, 2): no altermagnetic splitting possible.
        # Write the seekpath path directly as KPOINTS without butterfly insertion.
        is_triclinic = (centroid_result is not None
                        and centroid_result.get('spacegroup', 0) in (1, 2))
        if is_triclinic:
            print(f"\n[Note] Triclinic system (space group {centroid_result['spacegroup']}) detected.")
            print("  No altermagnetic splitting — writing standard seekpath k-path.")
            print(f"\n{BOLD}>>> Step 5: Save modified file{RESET}")
            print("Enter output filename (default: KPOINTS_modified): ", end='', flush=True)
            output_file = input().strip()
            if not output_file:
                output_file = "KPOINTS_modified"
            # Write the plain seekpath path (no butterfly, no transformation)
            self.write_kpoints_file(self.kpoints_data, output_file, None)
            print(f"\nProcess completed successfully!")
            return

        # Step 2: Auto-compute or manually enter general k-point
        print(f"\n{BOLD}>>> Step 2: Enter general k-point coordinates{RESET}")
        general_kpoint = None

        if centroid_result is not None:
            try:
                c = centroid_result['centroid_frac']
                general_kpoint = [c[0], c[1], c[2]]
                print(f"General k-point (IBZ centroid): [{c[0]:.6f}, {c[1]:.6f}, {c[2]:.6f}]")
            except Exception as e:
                print(f"[Warning] Centroid retrieval failed: {e}")
        elif struct_file and CENTROID_AVAILABLE:
            try:
                print(f"Computing IBZ centroid from '{struct_file}'...")
                result = compute_centroid(struct_file, output_dir='.', show_plot=True)
                c = result['centroid_frac']
                general_kpoint = [c[0], c[1], c[2]]
                print(f"General k-point (IBZ centroid): [{c[0]:.6f}, {c[1]:.6f}, {c[2]:.6f}]")
            except Exception as e:
                print(f"[Warning] Centroid computation failed: {e}")

        # Append centroid to spin_operations.txt for reference
        if general_kpoint is not None:
            try:
                with open("spin_operations.txt", "a") as f:
                    f.write(f"\nGeneral k-point (IBZ centroid, fractional): "
                            f"[{general_kpoint[0]:.6f}, {general_kpoint[1]:.6f}, {general_kpoint[2]:.6f}]\n")
            except Exception:
                pass

        if general_kpoint is None:
            print("Format: kx ky kz (space-separated)")
            while True:
                try:
                    print("Enter k-point: ", end='', flush=True)
                    k_input = input().strip().split()
                    if len(k_input) == 3:
                        general_kpoint = [float(x) for x in k_input]
                        break
                    else:
                        print("Please enter exactly 3 coordinates.")
                except ValueError:
                    print("Invalid input. Please enter three numbers.")

        # Step 3: Input transformation matrix
        print(f"\n{BOLD}>>> Step 3: Selecting Transformation Matrix R{RESET}")
        flip_ops = self.load_flip_operations()

        R = None
        if flip_ops:
            print(f"Found {len(flip_ops)} pre-calculated spin-flip operations:")
            for i, op in enumerate(flip_ops):
                print(f"\n  Option {i+1}:")
                # PRINTING MATRIX IN 3x3 FORMAT
                for row in op:
                    # Integer formatting if integer, else float
                    row_str = " ".join([f"{x: .0f}" if x.is_integer() else f"{x: .2f}" for x in row])
                    print(f"    [ {row_str} ]")

            print(f"\n  Note: all options produce equivalent band structures —")
            print(f"  k' = R⁻ᵀk always lands in the opposite-spin IBZ for any spin-flip R.")
            print(f"\nSelect an operation number (1-{len(flip_ops)})")
            print("Press [Enter] for default (1), or type number: ", end='', flush=True)
            choice = input().strip()

            if not choice:
                R = flip_ops[0]
                print("Selected default: Option 1")
            else:
                try:
                    idx = int(choice) - 1
                    if 0 <= idx < len(flip_ops):
                        R = flip_ops[idx]
                        print(f"Selected: Option {idx+1}")
                    else:
                        print("Invalid selection, falling back to manual input.")
                except ValueError:
                    print("Invalid input, falling back to manual input.")

        if R is None:
            print("No valid operations found or selected. Please enter manually.")
            print("Enter row by row (3 numbers per row, space-separated):")
            transformation_matrix = []
            for i in range(3):
                while True:
                    try:
                        print(f"Row {i+1}: ", end='', flush=True)
                        row_input = input().strip().split()
                        if len(row_input) == 3:
                            transformation_matrix.append([float(x) for x in row_input])
                            break
                        print("Please enter exactly 3 numbers.")
                    except ValueError: pass
            R = np.array(transformation_matrix)
        
        # Step 4: Process k-points
        print(f"\n{BOLD}>>> Step 4: Processing k-points...{RESET}")
        # Showing full matrix for confirmation
        print(f"Using Transformation Matrix R:")
        for row in R:
            print(f"  {row}")
            
        # Calculate and show k'
        k_prime = self.transform_kpoint(general_kpoint, R)
        print(f"k' (transformed k): [{k_prime[0]:.4f}, {k_prime[1]:.4f}, {k_prime[2]:.4f}]")
        
        try:
            new_kpoints = self.insert_general_kpoints(general_kpoint, R)
            
            if new_kpoints:
                # Step 5: Save modified file
                print(f"\n{BOLD}>>> Step 5: Save modified file{RESET}")
                print("Enter output filename (default: KPOINTS_modified): ", end='', flush=True)
                output_file = input().strip()
                if not output_file:
                    output_file = "KPOINTS_modified"
                
                self.write_kpoints_file(new_kpoints, output_file,R)
                print(f"\nProcess completed successfully!")
            else:
                print("Error: Failed to process k-points.")
                
        except Exception as e:
            print(f"Error processing k-points: {e}")

if __name__ == "__main__":
    modifier = KPointsModifier()
    modifier.interactive_modify()
